export const provinsiData = [
  {
    name: "Aceh",
    cities: [
      "Banda Aceh",
      "Langsa",
      "Lhokseumawe",
      "Sabang",
      "Subulussalam",
      "Aceh Barat",
      "Aceh Barat Daya",
      "Aceh Besar",
      "Aceh Jaya",
      "Aceh Selatan",
      "Aceh Singkil",
      "Aceh Tamiang",
      "Aceh Tengah",
      "Aceh Tenggara",
      "Aceh Timur",
      "Aceh Utara",
      "Bener Meriah",
      "Bireuen",
      "Gayo Lues",
      "Nagan Raya",
      "Pidie",
      "Pidie Jaya",
      "Simeulue",
    ],
  },
  {
    name: "Sumatera Utara",
    cities: [
      "Medan",
      "Binjai",
      "Gunungsitoli",
      "Padang Sidempuan",
      "Pematangsiantar",
      "Sibolga",
      "Tanjungbalai",
      "Tebing Tinggi",
      "Asahan",
      "Batubara",
      "Dairi",
      "Deli Serdang",
      "Humbang Hasundutan",
      "Karo",
      "Labuhanbatu",
      "Labuhanbatu Selatan",
      "Labuhanbatu Utara",
      "Langkat",
      "Mandailing Natal",
      "Nias",
      "Nias Barat",
      "Nias Selatan",
      "Nias Utara",
      "Padang Lawas",
      "Padang Lawas Utara",
      "Pakpak Bharat",
      "Samosir",
      "Serdang Bedagai",
      "Simalungun",
      "Tapanuli Selatan",
      "Tapanuli Tengah",
      "Tapanuli Utara",
      "Toba",
    ],
  },
  {
    name: "Sumatera Barat",
    cities: [
      "Padang",
      "Bukittinggi",
      "Padang Panjang",
      "Pariaman",
      "Payakumbuh",
      "Sawahlunto",
      "Solok",
      "Agam",
      "Dharmasraya",
      "Kepulauan Mentawai",
      "Lima Puluh Kota",
      "Padang Pariaman",
      "Pasaman",
      "Pasaman Barat",
      "Pesisir Selatan",
      "Sijunjung",
      "Solok Selatan",
      "Tanah Datar",
    ],
  },
  {
    name: "Riau",
    cities: [
      "Pekanbaru",
      "Dumai",
      "Bengkalis",
      "Indragiri Hilir",
      "Indragiri Hulu",
      "Kampar",
      "Kepulauan Meranti",
      "Kuantan Singingi",
      "Pelalawan",
      "Rokan Hilir",
      "Rokan Hulu",
      "Siak",
    ],
  },
  {
    name: "Kepulauan Riau",
    cities: [
      "Batam",
      "Tanjung Pinang",
      "Bintan",
      "Karimun",
      "Kepulauan Anambas",
      "Lingga",
      "Natuna",
    ],
  },
  {
    name: "Jambi",
    cities: [
      "Jambi",
      "Sungai Penuh",
      "Batanghari",
      "Bungo",
      "Kerinci",
      "Merangin",
      "Muaro Jambi",
      "Sarolangun",
      "Tanjung Jabung Barat",
      "Tanjung Jabung Timur",
      "Tebo",
    ],
  },
  {
    name: "Sumatera Selatan",
    cities: [
      "Palembang",
      "Lubuklinggau",
      "Pagar Alam",
      "Prabumulih",
      "Banyuasin",
      "Empat Lawang",
      "Lahat",
      "Muara Enim",
      "Musi Banyuasin",
      "Musi Rawas",
      "Musi Rawas Utara",
      "Ogan Ilir",
      "Ogan Komering Ilir",
      "Ogan Komering Ulu",
      "Ogan Komering Ulu Selatan",
      "Ogan Komering Ulu Timur",
      "Penukal Abab Lematang Ilir",
    ],
  },
  {
    name: "Bangka Belitung",
    cities: [
      "Pangkal Pinang",
      "Bangka",
      "Bangka Barat",
      "Bangka Selatan",
      "Bangka Tengah",
      "Belitung",
      "Belitung Timur",
    ],
  },
  {
    name: "Bengkulu",
    cities: [
      "Bengkulu",
      "Bengkulu Selatan",
      "Bengkulu Tengah",
      "Bengkulu Utara",
      "Kaur",
      "Kepahiang",
      "Lebong",
      "Mukomuko",
      "Rejang Lebong",
      "Seluma",
    ],
  },
  {
    name: "Lampung",
    cities: [
      "Bandar Lampung",
      "Metro",
      "Lampung Barat",
      "Lampung Selatan",
      "Lampung Tengah",
      "Lampung Timur",
      "Lampung Utara",
      "Mesuji",
      "Pesawaran",
      "Pesisir Barat",
      "Pringsewu",
      "Tanggamus",
      "Tulang Bawang",
      "Tulang Bawang Barat",
      "Way Kanan",
    ],
  },
  {
    name: "DKI Jakarta",
    cities: [
      "Jakarta Pusat",
      "Jakarta Utara",
      "Jakarta Barat",
      "Jakarta Selatan",
      "Jakarta Timur",
      "Kepulauan Seribu",
    ],
  },
  {
    name: "Jawa Barat",
    cities: [
      "Kota Bandung",
      "Banjar",
      "Kota Bekasi",
      "Kota Bogor",
      "Cimahi",
      "Kota Cirebon",
      "Depok",
      "Kota Sukabumi",
      "Kota Tasikmalaya",
      "Kabupaten Bandung",
      "Kabupaten Bandung Barat",
      "Kabupaten Bekasi",
      "Kabupaten Bogor",
      "Ciamis",
      "Cianjur",
      "Kabupaten Cirebon",
      "Garut",
      "Indramayu",
      "Karawang",
      "Kuningan",
      "Majalengka",
      "Pangandaran",
      "Purwakarta",
      "Subang",
      "Kabupaten Sukabumi",
      "Sumedang",
      "Kabupaten Tasikmalaya",
    ],
  },
  {
    name: "Banten",
    cities: [
      "Cilegon",
      "Kota Serang",
      "Kota Tangerang",
      "Tangerang Selatan",
      "Lebak",
      "Pandeglang",
      "Kabupaten Serang",
      "Kabupaten Tangerang",
    ],
  },
  {
    name: "Jawa Tengah",
    cities: [
      "Kota Semarang",
      "Kota Magelang",
      "Kota Pekalongan",
      "Salatiga",
      "Surakarta",
      "Kota Tegal",
      "Banjarnegara",
      "Banyumas",
      "Batang",
      "Blora",
      "Boyolali",
      "Brebes",
      "Cilacap",
      "Demak",
      "Grobogan",
      "Jepara",
      "Karanganyar",
      "Kebumen",
      "Kendal",
      "Klaten",
      "Kudus",
      "Kabupaten Magelang",
      "Pati",
      "Kabupaten Pekalongan",
      "Pemalang",
      "Purbalingga",
      "Purworejo",
      "Rembang",
      "Kabupaten Semarang",
      "Sragen",
      "Sukoharjo",
      "Kabupaten Tegal",
      "Temanggung",
      "Wonogiri",
      "Wonosobo",
    ],
  },
  {
    name: "DI Yogyakarta",
    cities: [
      "Yogyakarta",
      "Bantul",
      "Gunungkidul",
      "Kulon Progo",
      "Sleman",
    ],
  },
  {
    name: "Jawa Timur",
    cities: [
      "Surabaya",
      "Batu",
      "Kota Blitar",
      "Kota Kediri",
      "Kota Madiun",
      "Kota Malang",
      "Kota Mojokerto",
      "Kota Pasuruan",
      "Kota Probolinggo",
      "Bangkalan",
      "Banyuwangi",
      "Kabupaten Blitar",
      "Bojonegoro",
      "Bondowoso",
      "Gresik",
      "Jember",
      "Jombang",
      "Kabupaten Kediri",
      "Lamongan",
      "Lumajang",
      "Kabupaten Madiun",
      "Magetan",
      "Kabupaten Malang",
      "Kabupaten Mojokerto",
      "Nganjuk",
      "Ngawi",
      "Pacitan",
      "Pamekasan",
      "Kabupaten Pasuruan",
      "Ponorogo",
      "Kabupaten Probolinggo",
      "Sampang",
      "Sidoarjo",
      "Situbondo",
      "Sumenep",
      "Trenggalek",
      "Tuban",
      "Tulungagung",
    ],
  },
  {
    name: "Bali",
    cities: [
      "Denpasar",
      "Badung",
      "Bangli",
      "Buleleng",
      "Gianyar",
      "Jembrana",
      "Karangasem",
      "Klungkung",
      "Tabanan",
    ],
  },
  {
    name: "Nusa Tenggara Barat",
    cities: [
      "Mataram",
      "Kota Bima",
      "Kabupaten Bima",
      "Dompu",
      "Lombok Barat",
      "Lombok Tengah",
      "Lombok Timur",
      "Lombok Utara",
      "Sumbawa",
      "Sumbawa Barat",
    ],
  },
  {
    name: "Nusa Tenggara Timur",
    cities: [
      "Kota Kupang",
      "Alor",
      "Belu",
      "Ende",
      "Flores Timur",
      "Kabupaten Kupang",
      "Lembata",
      "Malaka",
      "Manggarai",
      "Manggarai Barat",
      "Manggarai Timur",
      "Nagekeo",
      "Ngada",
      "Rote Ndao",
      "Sabu Raijua",
      "Sikka",
      "Sumba Barat",
      "Sumba Barat Daya",
      "Sumba Tengah",
      "Sumba Timur",
      "Timor Tengah Selatan",
      "Timor Tengah Utara",
    ],
  },
  {
    name: "Kalimantan Barat",
    cities: [
      "Pontianak",
      "Singkawang",
      "Bengkayang",
      "Kapuas Hulu",
      "Kayong Utara",
      "Ketapang",
      "Kubu Raya",
      "Landak",
      "Melawi",
      "Mempawah",
      "Sambas",
      "Sanggau",
      "Sekadau",
      "Sintang",
    ],
  },
  {
    name: "Kalimantan Tengah",
    cities: [
      "Palangka Raya",
      "Barito Selatan",
      "Barito Timur",
      "Barito Utara",
      "Gunung Mas",
      "Kapuas",
      "Katingan",
      "Kotawaringin Barat",
      "Kotawaringin Timur",
      "Lamandau",
      "Murung Raya",
      "Pulang Pisau",
      "Seruyan",
      "Sukamara",
    ],
  },
  {
    name: "Kalimantan Selatan",
    cities: [
      "Banjarmasin",
      "Banjarbaru",
      "Balangan",
      "Banjar",
      "Barito Kuala",
      "Hulu Sungai Selatan",
      "Hulu Sungai Tengah",
      "Hulu Sungai Utara",
      "Kotabaru",
      "Tabalong",
      "Tanah Bumbu",
      "Tanah Laut",
      "Tapin",
    ],
  },
  {
    name: "Kalimantan Timur",
    cities: [
      "Balikpapan",
      "Bontang",
      "Samarinda",
      "Berau",
      "Kutai Barat",
      "Kutai Kartanegara",
      "Kutai Timur",
      "Mahakam Ulu",
      "Paser",
      "Penajam Paser Utara",
    ],
  },
  {
    name: "Kalimantan Utara",
    cities: [
      "Tarakan",
      "Bulungan",
      "Malinau",
      "Nunukan",
      "Tana Tidung",
    ],
  },
  {
    name: "Sulawesi Utara",
    cities: [
      "Manado",
      "Bitung",
      "Kotamobagu",
      "Tomohon",
      "Bolaang Mongondow",
      "Bolaang Mongondow Selatan",
      "Bolaang Mongondow Timur",
      "Bolaang Mongondow Utara",
      "Kepulauan Sangihe",
      "Kepulauan Siau Tagulandang Biaro",
      "Kepulauan Talaud",
      "Minahasa",
      "Minahasa Selatan",
      "Minahasa Tenggara",
      "Minahasa Utara",
    ],
  },
  {
    name: "Gorontalo",
    cities: [
      "Kota Gorontalo",
      "Boalemo",
      "Bone Bolango",
      "Kabupaten Gorontalo",
      "Gorontalo Utara",
      "Pohuwato",
    ],
  },
  {
    name: "Sulawesi Tengah",
    cities: [
      "Palu",
      "Banggai",
      "Banggai Kepulauan",
      "Banggai Laut",
      "Buol",
      "Donggala",
      "Morowali",
      "Morowali Utara",
      "Parigi Moutong",
      "Poso",
      "Sigi",
      "Tojo Una-Una",
      "Tolitoli",
    ],
  },
  {
    name: "Sulawesi Selatan",
    cities: [
      "Makassar",
      "Palopo",
      "Parepare",
      "Bantaeng",
      "Barru",
      "Bone",
      "Bulukumba",
      "Enrekang",
      "Gowa",
      "Jeneponto",
      "Kepulauan Selayar",
      "Luwu",
      "Luwu Timur",
      "Luwu Utara",
      "Maros",
      "Pangkajene dan Kepulauan",
      "Pinrang",
      "Sidenreng Rappang",
      "Sinjai",
      "Soppeng",
      "Takalar",
      "Tana Toraja",
      "Toraja Utara",
      "Wajo",
    ],
  },
  {
    name: "Sulawesi Barat",
    cities: [
      "Mamuju",
      "Majene",
      "Mamasa",
      "Kabupaten Mamuju",
      "Mamuju Tengah",
      "Pasangkayu",
      "Polewali Mandar",
    ],
  },
  {
    name: "Sulawesi Tenggara",
    cities: [
      "Kendari",
      "Baubau",
      "Bombana",
      "Buton",
      "Buton Selatan",
      "Buton Tengah",
      "Buton Utara",
      "Kolaka",
      "Kolaka Timur",
      "Kolaka Utara",
      "Konawe",
      "Konawe Kepulauan",
      "Konawe Selatan",
      "Konawe Utara",
      "Muna",
      "Muna Barat",
      "Wakatobi",
    ],
  },
  {
    name: "Maluku",
    cities: [
      "Ambon",
      "Tual",
      "Buru",
      "Buru Selatan",
      "Kepulauan Aru",
      "Kepulauan Tanimbar",
      "Maluku Barat Daya",
      "Maluku Tengah",
      "Maluku Tenggara",
      "Seram Bagian Barat",
      "Seram Bagian Timur",
    ],
  },
  {
    name: "Maluku Utara",
    cities: [
      "Ternate",
      "Tidore Kepulauan",
      "Halmahera Barat",
      "Halmahera Selatan",
      "Halmahera Tengah",
      "Halmahera Timur",
      "Halmahera Utara",
      "Kepulauan Sula",
      "Pulau Morotai",
      "Pulau Taliabu",
    ],
  },
  {
    name: "Papua",
    cities: [
      "Kota Jayapura",
      "Biak Numfor",
      "Kabupaten Jayapura",
      "Keerom",
      "Kepulauan Yapen",
      "Mamberamo Raya",
      "Sarmi",
      "Supiori",
      "Waropen",
    ],
  },
  {
    name: "Papua Barat",
    cities: [
      "Kota Manokwari",
      "Fakfak",
      "Kaimana",
      "Kabupaten Manokwari",
      "Manokwari Selatan",
      "Pegunungan Arfak",
      "Teluk Bintuni",
      "Teluk Wondama",
    ],
  },
  {
    name: "Papua Barat Daya",
    cities: [
      "Kota Sorong",
      "Maybrat",
      "Raja Ampat",
      "Kabupaten Sorong",
      "Sorong Selatan",
      "Tambrauw",
    ],
  },
  {
    name: "Papua Pegunungan",
    cities: [
      "Jayawijaya",
      "Lanny Jaya",
      "Mamberamo Tengah",
      "Nduga",
      "Pegunungan Bintang",
      "Tolikara",
      "Yahukimo",
      "Yalimo",
    ],
  },
  {
    name: "Papua Selatan",
    cities: [
      "Merauke",
      "Asmat",
      "Boven Digoel",
      "Mappi",
    ],
  },
  {
    name: "Papua Tengah",
    cities: [
      "Nabire",
      "Deiyai",
      "Dogiyai",
      "Intan Jaya",
      "Mimika",
      "Paniai",
      "Puncak",
      "Puncak Jaya",
    ],
  },
];

export function getCitiesForProvince(provinceName: string): string[] {
  const province = provinsiData.find((p) => p.name === provinceName);
  return province ? province.cities : [];
}
